# Generated by Django 3.0 on 2022-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20221117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cameras'), ('L', 'Laptops'), ('S', 'Smartphones'), ('A', 'Accessories')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('S', 'sale')], max_length=1, null=True),
        ),
    ]
