# Generated by Django 3.0 on 2022-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20221117_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Accessories'), ('S', 'Smartphones'), ('L', 'Laptops'), ('C', 'Cameras')], max_length=2),
        ),
    ]
