# Generated by Django 3.0 on 2022-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_auto_20221123_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recieved',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cameras'), ('L', 'Laptops'), ('S', 'Smartphones'), ('A', 'Accessories')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('S', 'sale')], max_length=1, null=True),
        ),
    ]
