# Generated by Django 3.0 on 2022-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_auto_20221123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Accessories'), ('S', 'Smartphones'), ('C', 'Cameras'), ('L', 'Laptops')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('S', 'sale')], max_length=1, null=True),
        ),
    ]
