# Generated by Django 3.0 on 2022-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20221201_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Smartphones'), ('A', 'Accessories'), ('L', 'Laptops'), ('C', 'Cameras')], max_length=2),
        ),
    ]
