# Generated by Django 3.0 on 2022-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_auto_20221203_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'Laptops'), ('S', 'Smartphones'), ('A', 'Accessories'), ('C', 'Cameras')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'sale'), ('N', 'new')], max_length=1, null=True),
        ),
    ]
