# Generated by Django 3.0 on 2022-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_auto_20221205_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cameras'), ('A', 'Accessories'), ('S', 'Smartphones'), ('L', 'Laptops')], max_length=2),
        ),
    ]
