# Generated by Django 3.0 on 2022-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_auto_20221205_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Accessories'), ('C', 'Cameras'), ('L', 'Laptops'), ('S', 'Smartphones')], max_length=2),
        ),
    ]
