# Generated by Django 3.0 on 2022-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0025_auto_20221206_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cameras'), ('A', 'Accessories'), ('L', 'Laptops'), ('S', 'Smartphones')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'sale'), ('N', 'new')], max_length=1, null=True),
        ),
    ]
